### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [joepvd/senv#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by joepvd** [comment]
Thanks for your interest! 

Added [unlicense](https://github.com/joepvd/senv/commit/06680070e8b91ead7b49c0bd1db2eec7d378ce1f).
